// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20260204221809_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Model.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GameTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrizeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Model.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWonGift")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSessionStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaysRemaining")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1234567,
                            HasWonGift = false,
                            LastSessionStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaysRemaining = 3
                        });
                });

            modelBuilder.Entity("Model.Prize", b =>
                {
                    b.Property<int>("PrizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("PrizeId");

                    b.ToTable("Prizes");

                    b.HasData(
                        new
                        {
                            PrizeId = 1,
                            Description = "No Prize",
                            Weight = 0.5m
                        },
                        new
                        {
                            PrizeId = 2,
                            Description = "$5 Free Play",
                            Weight = 0.25m
                        },
                        new
                        {
                            PrizeId = 3,
                            Description = "$10 Free Play",
                            Weight = 0.15m
                        },
                        new
                        {
                            PrizeId = 4,
                            Description = "Food Voucher",
                            Weight = 0.07m
                        },
                        new
                        {
                            PrizeId = 5,
                            Description = "Gift Item",
                            Weight = 0.03m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
